#!/usr/bin/env python

import matplotlib
matplotlib.use("qt4agg")
import matplotlib.pyplot as plt
import argparse
import acis_pytools
from acis_pytools.utils import msid_units

parser = argparse.ArgumentParser()
parser.add_argument("tracelog", type=str)
parser.add_argument("plots", type=str)
args = parser.parse_args()

states = []
msids = []

for p in args.plots.split(','):
    if p in msid_units:
        msids.append(p)
    else:
        states.append(p)

fields = [("msids", m) for m in msids] + [("states", s) for s in states]

if len(states) == 0:
    states = None

ds = acis_pytools.DataSource.fetch_from_tracelog(args.tracelog, state_keys=states)
cp = acis_pytools.MultiDatePlot(ds, fields)

plt.show()