#!/usr/bin/env python

import matplotlib
matplotlib.use("qt4agg")
import matplotlib.pyplot as plt
import argparse
import acis
from acis.utils import msid_units

parser = argparse.ArgumentParser()
parser.add_argument("tstart", type=str)
parser.add_argument("tstop", type=str)
parser.add_argument("plots", type=str)
args = parser.parse_args()

states = []
msids = []

for p in args.plots.split(','):
    if p in msid_units:
        msids.append(p)
    else:
        states.append(p)

ds = acis.DataSource()
ds.get_msids.from_archive(msids, args.tstart, tstop=args.tstop)
ds.get_states.from_database(states, args.tstart, args.tstop)

fields = [("msids", m) for m in msids] + [("states", s) for s in states]

cp = acis.MultiDatePlot(ds, fields)

plt.show()