#!/usr/bin/env python

import argparse
from acis.obscat import ObsID

parser = argparse.ArgumentParser()
parser.add_argument("obsid", type=str)
parser.add_argument("--chaser", action="store_true")

args = parser.parse_args()

obsid = ObsID(args.obsid)

obsid.open_obscat_data_page()
if args.chaser:
    obsid.open_chaser()