#!/usr/bin/env python

import matplotlib
matplotlib.use("qt4agg")
import matplotlib.pyplot as plt
import argparse
import acis_pytools
from acis_pytools.utils import msid_units

parser = argparse.ArgumentParser()
parser.add_argument("tstart", type=str)
parser.add_argument("tstop", type=str)
parser.add_argument("y_axis", type=str)
parser.add_argument("--y2_axis", type=str)
args = parser.parse_args()

msids = []
states = []
if args.y_axis in msid_units:
    msids.append(args.y_axis)
    y_axis = ("msids", args.y_axis)
else:
    states.append(args.y_axis)
    y_axis = ("states", args.y_axis)
if args.y2_axis is not None:
    if args.y2_axis in msid_units:
        msids.append(args.y2_axis)
        y2_axis = ("msids", args.y2_axis)
    else:
        states.append(args.y2_axis)
        y2_axis = ("states", args.y2_axis)
else:
    y2_axis = None

ds = acis_pytools.DataSource()
ds.get_msids.from_database(msids, args.tstart, tstop=args.tstop)
ds.get_states.from_database(states, args.tstart, args.tstop)

cp = acis_pytools.DatePlot(ds, y_axis, field2=y2_axis)
plt.show()