#!/usr/bin/env python

import argparse
import acispy
from acispy.utils import mylog
import numpy as np

short_name = {"dea": "1deamzt",
              "dpa": "1dpamzt",
              "psmc": "1pdeaat",
              "bep_pcb": "tmp_bep_pcb",
              "fep1_mong": "tmp_fep1_mong",
              "fep1_actel": "tmp_fep1_actel"}

parser = argparse.ArgumentParser(description='Simulate an ECS run.')
parser.add_argument("component", type=str, help='The component to model: dpa, dea, or psmc.')
parser.add_argument("tstart", type=str, help='The start time of the ECS run in YYYY:DOY:HH:MM:SS format')
parser.add_argument("hours", type=float, help='The length of the ECS run in hours.')
parser.add_argument("T_init", type=float, help='The initial temperature of the component in degrees C.')
parser.add_argument("pitch", type=float, help='The pitch in degrees.')
parser.add_argument("ccd_count", type=int, help="The number of CCDs to clock.")
parser.add_argument("--vehicle_load", type=str, 
                    help="The vehicle load which is running. Default: None, meaning no vehicle "
                         "load. If this parameter is set, the input values of pitch and "
                         "off-nominal roll will be ignored and the values from the vehicle load "
                         "will be used.")
parser.add_argument("--simpos", type=float, default=-99616.0, help="The SIM position. Default: -99616.0")
parser.add_argument("--off_nom_roll", type=float, default=0.0, help="The off-nominal roll. Default: 0.0")
parser.add_argument("--dh_heater", type=int, default=0, help="Is the DH heater on (1) or off (0)? Default: 0/off.")
parser.add_argument("--fep_count", type=int, help="The number of FEPs which are on.")
parser.add_argument("--clocking", type=int, default=1, help="Whether or not the CCDs are being clocked.")
parser.add_argument("--instrument", type=str, help="The instrument which is being used, only for the FP temperature.")
parser.add_argument("--q", type=str, help="Target quaternion in the case of the FP temperature.")

args = parser.parse_args()


if args.component in ["fptemp_11", "acis_fp"] and args.q is not None:
    q = np.array(args.q.split(',')).astype("float64")
else:
    q = args.q

ecs_run = acispy.SimulateECSRun(args.component, args.tstart, args.hours, args.T_init,
                                args.pitch, args.ccd_count, vehicle_load=args.vehicle_load,
                                simpos=args.simpos, off_nom_roll=args.off_nom_roll, 
                                dh_heater=args.dh_heater, fep_count=args.fep_count,
                                clocking=args.clocking, instrument=args.instrument, q=q)

dp = ecs_run.plot_model()
filename = "ecs_run_%s_%dchip_%s.png" % (args.component, args.ccd_count, args.tstart)
dp.savefig(filename)
mylog.info("Image of the model run has been written to %s." % filename)
